apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-sa
  namespace: analytics-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::278375639105:role/analytics-service-role
