apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-sa
  namespace: analytics-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::052058222675:role/toggle-master-prod-analytics-service-role
