apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation-service   
  labels:
    app: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      serviceAccountName: evaluation-service-sa   
      containers:
        - name: evaluation-service
          image: 052058222675.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:sha-3da5119
          ports:
            - containerPort: 8004
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secret
                  key: SERVICE_API_KEY
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AUTH_SERVICE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: REDIS_URL
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: FLAG_SERVICE_URL
            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: TARGETING_SERVICE_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_REGION
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_SQS_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: PORT
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
