apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service-sa
  namespace: evaluation-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::052058222675:role/toggle-master-prod-evaluation-service-role
