apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service-sa
  namespace: evaluation-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::278375639105:role/evaluation-service-role
