apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"metrics-server","meta.helm.sh/release-namespace":"kube-system"},"creationTimestamp":"2026-07-05T21:07:54Z","labels":{"app.kubernetes.io/instance":"metrics-server","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"metrics-server","app.kubernetes.io/version":"0.8.1","helm.sh/chart":"metrics-server-3.13.1","k8s-app":"metrics-server"},"name":"metrics-server","namespace":"kube-system","resourceVersion":"79771","uid":"b235dcba-553d-46eb-a042-af94bd8e1e55"},"spec":{"clusterIP":"10.96.181.36","clusterIPs":["10.96.181.36"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"appProtocol":"https","name":"https","port":443,"protocol":"TCP","targetPort":4443}],"selector":{"app.kubernetes.io/instance":"metrics-server","app.kubernetes.io/name":"metrics-server","k8s-app":"metrics-server"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: metrics-server
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2026-07-05T21:07:54Z"
  labels:
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/version: 0.8.1
    helm.sh/chart: metrics-server-3.13.1
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
  resourceVersion: "80167"
  uid: b235dcba-553d-46eb-a042-af94bd8e1e55
spec:
  clusterIP: 10.96.181.36
  clusterIPs:
  - 10.96.181.36
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: 4443
  selector:
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/name: metrics-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
