apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting-service   
  labels:
    app: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      serviceAccountName: targeting-service-sa   
      containers:
        - name: targeting-service
          image: 
          ports:
            - containerPort: 8003
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: DB_PASS
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: AUTH_SERVICE_URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: DB_NAME
            - name: SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: SSL_MODE
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
