apiVersion: v1
kind: ServiceAccount
metadata:
  name: targeting-service-sa
  namespace: targeting-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::052058222675:role/toggle-master-prod-targeting-service-role
