apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
type: Opaque
data:
  DB_USER: YXV0aA==   
  DB_PASS: YmEuX1s2RHIzdyp8ZERLNHMjakhXZyNHcFQ4IQ==
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
