apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
type: Opaque
data:
  # DB_USER = auth_user, DB_PASS = auth_db_password (must match RDS credentials set in terraform.tfvars)
  DB_USER: YXV0aF91c2Vy
  DB_PASS: YXV0aF9kYl9wYXNzd29yZA==
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
