apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: auth-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::052058222675:role/toggle-master-prod-auth-service-role
