apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ArgoCD's app-of-apps Application points at this folder.
# Each resource here is an ArgoCD Application CR for one service.

resources:
  - auth-service-app.yaml
  - flag-service-app.yaml
  - targeting-service-app.yaml
  - evaluation-service-app.yaml
  - analytics-service-app.yaml
