apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: flag-service
type: Opaque
data:
  # DB_USER = flag_user, DB_PASS = flag_db_password (must match RDS credentials in terraform.tfvars)
  DB_USER: ZmxhZ191c2Vy
  DB_PASS: ZmxhZ19kYl9wYXNzd29yZA==
