apiVersion: v1
kind: ServiceAccount
metadata:
  name: flag-service-sa
  namespace: flag-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::052058222675:role/toggle-master-prod-flag-service-role
